config/routes.rb
Rails.application.routes.draw do
  devise_for :users 
  devise_scope :user do
    authenticated  do
      root to: 'customers#main'
      get '/users/sign_out' => 'devise/sessions#destroy'     
    end

    unauthenticated do
      root to: 'devise/sessions#new', as: 'unauthenticated_root'
    end
  end
  get 'customers/main'
 
  resources :bookings
  resources :cleaners
  resources :customers  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :cleaner

  validates :customer_name,  presence: true
  validates :cleaner_name, presence: true
end

app/models/cleaner.rb
class Cleaner < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  belongs_to :booking ,optional: true

  validates :first_name,  presence: true
  validates :last_name, presence: true
  validates_numericality_of :quality_score, :less_than_or_equal_to  => 5.0
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }
end

app/models/customer.rb
class Customer < ApplicationRecord
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :first_name,  presence: true
	validates :last_name, presence: true
	validates_numericality_of :phone_number
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX }
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_booking, only: [:show, :edit, :update, :destroy]

  def index
    @bookings = Booking.all
  end

  def show
  end

  def new
    @booking = Booking.new
  end

  def edit
  end

  def create
    @booking = Booking.new(booking_params)
    cleaner = Cleaner.select(:first_name, :email)
    render 'new' unless @booking.save
    cleaner.each do |cleaner|
      if (@booking.cleaner_name == cleaner.first_name)
        UserMailer.welcome_email(cleaner).deliver_now
        redirect_to @booking
        end
      end  
  end

  def update
    if @booking.update(booking_params)
      redirect_to @booking
    else
      render 'edit'
    end
  end

  def destroy
    @booking.destroy
    redirect_to bookings_url
  end

  private
    def set_booking
      @booking = Booking.find(params[:id])
    end

    def booking_params
      params.require(:booking).permit(:customer_name, :cleaner_name, :date)
    end
end

app/controllers/cleaners_controller.rb
class CleanersController < ApplicationController
  before_action :set_cleaner, only: [:show, :edit, :update, :destroy]

  def index
    @cleaners = Cleaner.all
  end

  def show
  end

  def new
    @cleaner = Cleaner.new
  end

  def edit
  end

  def create
    @cleaner = Cleaner.new(cleaner_params)
    if @cleaner.save
      redirect_to @cleaner
    else
      render 'new'
    end
  end
  
  def update
    if @cleaner.update(cleaner_params)
      redirect_to @cleaner
    else
      render 'edit'
    end
  end

  def destroy
    @cleaner.destroy
    redirect_to cleaners_url
  end

  private

    def set_cleaner
      @cleaner = Cleaner.find(params[:id])
    end

    def cleaner_params
      params.require(:cleaner).permit(:first_name, :last_name, :email, :phone_number, :city, :quality_score)
    end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  def main
    render 'main'
  end

  def index
    @customers = Customer.all
  end

  def show
  end

  def new
    @customer = Customer.new
  end

  def edit
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def update
      if @customer.update(customer_params)
        redirect_to @customer
      else
        render 'edit'
      end
    
  end

  def destroy
    @customer.destroy
    redirect_to customers_url
  end

  private

    def set_customer
      @customer = Customer.find(params[:id])
    end

    def customer_params
      params.require(:customer).permit(:first_name, :last_name, :email, :phone_number, :city)
    end
end

app/views/bookings/_form.html.erb
<div data-controller='bookings'>
  <div class="right_col" role="main"style="min-height: 600px;">
    <%= form_with(model: @booking, local: true, class: 'form-horizontal form-label-left') do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="x_panel" style="min-height: 600px;">
        <h1><b>Booking</b>
        <div class="nav navbar-right panel_toolbox">
        <a class="btn  btn-info" href="<%=cleaners_path%>"><i class="fa fa-eye"></i>  See cleaners List</a>
        </div>
        </h1><br>

        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
          <%= t('bookings.customer_name') %>
          <span class="text-danger">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :customer_name, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
            <%= t('bookings.cleaner_name') %>
            <span class="text-danger">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :cleaner_name, class: 'form-control', required: true %>
          </div>
        </div>

        <div class="form-group">  
          <label class="control-label col-md-3 col-sm-3 col-xs-12">
            <%= t('bookings.date') %>
            <span class="text-danger">*</span>
          </label>
          <div class="col-md-6 col-sm-6 col-xs-12">
            <%= f.text_field :date, class: 'form-control', class: 'form-control', id: "datepicker", required: true %>
          </div>
        </div></br>
          
        <div class="form-group">
          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button class="btn btn-primary" type="reset">Reset</button>
            <button type="submit" class="btn btn-success">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<%=render 'layouts/home'%>
<%= render 'form', booking: @booking %>

app/views/bookings/index.html.erb
<%= render 'layouts/home'%>
<div class="right_col" role="main" style="min-height: 600px;"> 
  <div class="container">
    <h1>Displaying All Bookings</h1><br>
    <table class="table table-striped jambo_table bulk_action">
      <thead>
        <tr>
          <th>Customer Name</th>
          <th>Cleaner Name</th>
          <th> Date </th>
        </tr>
      </thead>
      <tbody>
        <% @bookings.each do |booking| %>
        <tr>
          <td><%= booking.customer_name %></td>
          <td><%= booking.cleaner_name %></td>
          <td><%= booking.date %></td>
        </tr>
        <% end %>
      </tbody>
    </table>
    </div>
  </div>
</div>

app/views/bookings/new.html.erb
<%=render 'layouts/home'%>
<%= render 'form', booking: @booking %>

app/views/bookings/show.html.erb
<%=render 'layouts/home'%>
<div class="right_col" role="main" style="min-height: 500px;">
<div class="x_panel" style="min-height: 600px;">
<div class="col-md-8 col-lg-8 col-sm-7">
<h3><%=t('Booking.main')%></h3>
<p>Details are : </p>
  <ul class="list-unstyled user_data">
    <li>
      <i class="fa fa-user"></i>  Customer : <%= @booking.customer_name %> 
    </li>
    <li>
      <i class="fa fa-user"></i>  Cleaner :  <%= @booking.cleaner_name %>
    </li>
    <li>
      <i class="fa fa-clock-o"></i>  Date : <%= @booking.date %>
    </li>
  </ul><br><br>
  <div>
    <a class="btn btn-success" href="<%=edit_booking_path(@booking)%>"><i class="fa fa-edit m-right-xs"></i> Edit Booking</a>
    <a class="btn btn-dark" href="<%=customers_main_path%>"><i class="fa fa-rotate-left m-right-xs"></i> Back To Home</a>                
  </div> 
</div>
</div>

app/views/cleaners/_form.html.erb
<div data-controller='cleaners'>
  <div class="right_col" role="main"style="min-height: 600px;">
    <%= form_with(model: @cleaner, local: true, class: 'form-horizontal form-label-left') do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="x_panel" style="min-height: 600px;">
          <h1><b>Cleaner</b></h1><br>
           <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('cleaners.first_name') %>
                <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :first_name, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('cleaners.last_name') %>
                <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :last_name, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">  
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                  <%= t('cleaners.email') %>
                  <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :email, class: 'form-control', required: true %>
               </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('cleaners.phone_number') %>
                <span class="text-danger">*</span>
              </label>
               <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :phone_number, class: 'form-control', required: true %>
                </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('cleaners.quality_score') %>
                <span class="text-danger">*</span>
              </label>
               <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :quality_score, class: 'form-control', required: true %>
                </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('cleaners.city') %>
                <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.select :city, options_for_select(CS.cities(:gj, :in)), {:prompt => "City"}, {:id => "city-picker"} %>
              </div>
            </div>
            </br>

            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
           </div>
         </form>
      </div>
    </div>
  </div>
</div>
<% end %>
</body>
</html>

app/views/cleaners/edit.html.erb
<%= render 'layouts/home'%>
<%= render 'form', user: @cleaner %>
<%= link_to 'Show', @cleaner %>

app/views/cleaners/index.html.erb
<%= render 'layouts/home'%>
<div class="right_col" role="main" style="min-height: 600px;"> 
  <div class="container">
    <h1>Cleaners List</h1><br>
      <table class="table table-striped jambo_table bulk_action">
        <thead>
          <tr>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>City</th>
            <th>Quality Score</th>
            <th>Book Cleaner</th>
          </tr>
          </thead>
          <tbody>
          <% @cleaners.each do |cleaner| %>
          <tr>
            <td><%= cleaner.first_name %></td>
            <td><%= cleaner.last_name %></td>
            <td><%= cleaner.email %></td>
            <td><%= cleaner.phone_number %></td>
            <td><%= cleaner.city %></td>
            <td><%= cleaner.quality_score %></td>
            <td> 
              <a class="btn btn-link" href="<%=new_booking_path(@booking)%>"><i class="fa fa-edit m-right-xs"></i>  Book</a>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/cleaners/new.html.erb
<%= render 'layouts/home'%>
<%= render 'form', customer: @cleaner %>

app/views/cleaners/show.html.erb
<%= render 'layouts/home'%>
  <div class="right_col" role="main" style="min-height: 600px;">
    <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel" style="min-height: 600px;">
            <div class="x_title">
              <h3>Cleaner Profile</h3>
                 <div class="clearfix"></div>
            </div>
            <div class="x_panel title fixed_height_320 overflow_hidden">
              <div class="col-md-8 col-lg-8 col-sm-7">
                <blockquote>
                  <%=t('Cleaner.show')%>
                </blockquote>
              </div>
              <div class="col-md-4 col-sm-4 col-xs-5">
              <ul class="list-unstyled user_data">
                <li>
                  <i class="fa fa-user"></i> <%= @cleaner.first_name %> <%= @cleaner.last_name %>
                </li>
                <li>
                  <i class="fa fa-map-marker user-profile-icon"></i>  <%= @cleaner.city %>
                </li>
                <li>
                  <i class="fa fa-envelope"></i> <%= @cleaner.email %>
                </li>
                <li>
                  <i class="fa fa-phone"></i> <%= @cleaner.phone_number %>
                </li>
                <li>
                  <i class="fa fa-star"></i> <%= @cleaner.quality_score %>
                </li>
              </ul>
            </div> 
            <a class="btn btn-success" href="<%=edit_cleaner_path(@cleaner)%>"><i class="fa fa-edit m-right-xs"></i> Edit Profile</a>
            <a class="btn btn-dark" href="<%=customers_main_path%>"><i class="fa fa-rotate-left m-right-xs"></i> Back To Home</a>                
          </div>
        </div>
      </div>
    </div>

app/views/customers/_form.html.erb
<div data-controller='customers'>
  <div class="right_col" role="main" style="min-height: 600px;">
    <%= form_with(model: @customer, local: true, class: 'form-horizontal form-label-left') do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
        <div class="x_panel" style="min-height: 600px;"><h1><b>Customer</b>
        <div class="nav navbar-right panel_toolbox">
        <h5>If Registered  <a class="btn btn-round btn-primary" href="<%=cleaners_path(@customer)%>"><i class="fa fa-edit m-right-xs"></i>  Book Cleaner</a>
        </div></h1><br>
          <div class="form-group">
            <label class="control-label col-md-3 col-sm-3 col-xs-12">
              <%= t('customers.first_name') %>
              <span class="text-danger">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
              <%= f.text_field :first_name, class: 'form-control', required: true %>
            </div>
          </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('customers.last_name') %>
                <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :last_name, class: 'form-control', required: true %>
              </div>
            </div>

            <div class="form-group">  
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                  <%= t('customers.email') %>
                  <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.text_field :email, class: 'form-control', required: true %>
               </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('customers.phone_number') %>
                <span class="text-danger">*</span>
              </label>
               <div class="col-md-6 col-sm-6 col-xs-12">
                  <%= f.text_field :phone_number, class: 'form-control', required: true %>
                </div>
            </div>

            <div class="form-group">
              <label class="control-label col-md-3 col-sm-3 col-xs-12">
                <%= t('customers.city') %>
                <span class="text-danger">*</span>
              </label>
              <div class="col-md-6 col-sm-6 col-xs-12">
                <%= f.select :city, options_for_select(CS.cities(:gj, :in)), {:prompt => "City"}, {:id => "city-picker"} %>
              </div>
            </div>  
            </br>

            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <button class="btn btn-primary" type="reset">Reset</button>
                <button type="submit" class="btn btn-success">Submit</button>
              </div>
           </div>
         </form>
      </div>
    </div>
  </div>
</div>
<% end %>
</body>
</html>

app/views/customers/edit.html.erb
<%= render 'layouts/home'%>
<%= render 'form', user: @customer %>

app/views/customers/index.html.erb
<%= render 'layouts/home'%>
<div class="right_col" role="main" style="min-height: 600px;"> 
<div class="container">
  <h1>Displaying All Customers</h1><br>
    <table class="table table-striped jambo_table bulk_action">
      <thead>
        <tr>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Phone Number</th>
          <th>City</th>
        </tr>
      </thead>
      <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.first_name %></td>
        <td><%= customer.last_name %></td>
        <td><%= customer.email %></td>
        <td><%= customer.phone_number %></td>
        <td><%= customer.city %></td>
      </tr>
      <% end %>
    </tbody>
    </table>
    </div>
  </div>
</div>

app/views/customers/main.html.erb
<%= render 'layouts/home'%>
<div class="right_col" role="main" style="min-height: 600px;">
  <div class="x_panel" style="min-height: 600px;">
    <div class="x_title">
			<div class="clearfix"></div>
				<div class="jumbotron">
      	  <h1>Welcome to HomeWorker</h1>
        </div>
				<%=t('Main.welcome')%>
			</div>
		</div>
	</div>
</div>	

app/views/customers/new.html.erb
<%= render 'layouts/home'%>
<%= render 'form', customer: @customer %>

app/views/customers/show.html.erb
<%= render 'layouts/home'%>
  <div class="right_col" role="main" style="min-height: 600px;">
    <div class="clearfix"></div>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel" style="min-height: 600px;">
            <div class="x_title">  <div class="nav navbar-right panel_toolbox">
            <a class="btn btn-dark" href="<%=customers_main_path%>"><i class="fa fa-rotate-left m-right-xs"></i> Back To Home</a>                
            </div>
              <h3>Customer Profile</h3>
                 <div class="clearfix">
                  </div>
                  </div>
                 <div class="x_panel title fixed_height_320 overflow_hidden">
                    <div class="col-md-8 col-lg-8 col-sm-7">
                      <blockquote>
                        <%=t('Customer.show')%>
                      </blockquote>
                    </div>
                  <div class="col-md-4 col-sm-4 col-xs-5">
                    <ul class="list-unstyled user_data">
                      <li>
                        <i class="fa fa-user"></i> <%= @customer.first_name %> <%= @customer.last_name %>
                      </li>
                      <li><i class="fa fa-map-marker user-profile-icon"></i>  <%= @customer.city %>
                      </li>
                      <li>
                        <i class="fa fa-envelope"></i> <%= @customer.email %>
                      </li>
                      <li>
                        <i class="fa fa-phone"></i> <%= @customer.phone_number %>
                      </li>
                    </ul>
                  </div> 
                  <a class="btn btn-success" href="<%=edit_customer_path(@customer)%>"><i class="fa fa-edit m-right-xs"></i> Edit Profile</a>
                  <a class="btn btn-primary" href="<%=cleaners_path%>"><i class="fa fa-edit m-right-xs"></i> Book Cleaner</a>             
                  </div>
            </div>
          </div>
        </div>
        

app/views/layouts/_home.html.erb
<!DOCTYPE html>
<html lang="en">
  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a class="site_title"><i class="fa fa-paw"></i> <span>Home Worker</span></a>
            </div>
            <br>
            <div class="clearfix"></div>
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li>
                    <a href="<%= customers_main_path %>">
                      <i class="fa fa-home">
                      </i> Home
                    </a>
                  </li>
                  <li>
                    <a href="<%= new_customer_path %>">
                    <i class="fa fa-user">
                    </i>Customers</a>
                  </li> 
                  <li>
                    <a href="<%=new_cleaner_path%>">
                      <i class="fa fa-user">
                      </i>Cleaners</a>
                  </li>
                  <li>
                    <a href="<%=new_booking_path%>">
                      <i class="fa fa-check-square-o">
                      </i>Booking</a>
                  </li>
                </ul>
              </div>
            </div>            
          </div>
        </div>
       <div class="nav navbar-nav navbar-right">
        <%= link_to "Logout", destroy_user_session_path %>
      </div>
    </div>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
      <%= yield %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>